### PR TITLE
Disable Lua Check global warnings in favor of LuaLS

### PR DESCRIPTION
**Pull request by emmericp**

### CODE REVIEW

**Comment by MysticalOS** [comment]
Also, too dumb to figure it out but was trying to define CheckDispelFilter to auto populate with the string options

**Comment by emmericp** [comment]
PTAL, with the new "only globals" check this doesn't change any functionality, but just gets rid of the annoyingly long globals list

**Review by QartemisT — APPROVED** [review]
Eventually, we want to completely kill Luacheck, correct?

**Comment by emmericp** [comment]
yes, i just want to be careful to not gate release on something that only i truly understand

**Pull request merged**
