### PR TITLE
Spanish Translates

### PR DESCRIPTION
**Pull request by Alysrazor**
Added missing translates by Alysrazor.

Translates are made by my own. Some words could be different in-game, but the meaning doesn't change.

### CODE REVIEW

**Comment by MysticalOS** [comment]
Just make sure that translations for actual triggers such as boss yells or emotes have to match blizzard or they are useless. It's best not to guess translate those and only translate the warning/option/core stuff

**Review by MysticalOS — CHANGES_REQUESTED** [review]
Just make sure that translations for actual triggers such as boss yells or emotes have to match blizzard or they are useless. It's best not to guess translate those and only translate the warning/option/core stuff

A lot of what you translated was boss lines/triggers and I don't want to merge those if they aren't a 100% match because it makes it more difficult to see which ones need correct blizzard strings.

**Comment by Alysrazor** [comment]
I'll revert the text phrases except the titles translations until I have the boss quotes.

**Comment by Alysrazor** [comment]
All bosses quotes are reverted to english. I will translate them as soon as possible. Only titles, options and misc have been translated.

**Review by MysticalOS — APPROVED** [review]

**Pull request merged**
