### PR TITLE
rename zhTW to localization.tw

### PR DESCRIPTION
**Pull request by BlueNightSky**
Sorry, I made a mistake.

### CODE REVIEW

**Review by QartemisT — APPROVED** [review]

**Comment by QartemisT** [comment]
There are no mistakes, only happy coincidences - Bob Ross.

**Comment by Molkree** [comment]
I think it should be `localization.tw.lua` (there's no `.lua` part right now) and it should be added to [.toc](https://github.com/DeadlyBossMods/DeadlyBossMods/blob/0d29ce3e3d2f6dcc50ebbc6dc5a5bacb9141dcc8/DBM-SanctumOfDomination/DBM-SanctumOfDomination.toc)

**Comment by MysticalOS** [comment]
just like artemis to merge a bad PR without actually reviewing it :D

**Comment by QartemisT** [comment]
THERE ARE NO MISTAKES, ONLY HAPPY COINCIDENCES - bOB rOSS

**Pull request merged**
