### PR TITLE
Core+DBT: implement variance timers

### PR DESCRIPTION
**Pull request by Zidras**
Fixes https://github.com/DeadlyBossMods/DBM-Unified/issues/265

Introduces variance framework onto the following methods:
- NewTimer
- newTimer
- Start

**Syntax**:
General purposes: `"v20.5-25.5"` , `local timerWithVarianceCD = mod:NewCDCountTimer("v36-40")`, `timerWithVarianceCD:Start("v5-10")`
With allowdouble: `"dv20.5-25.5"`

**Proposed syntax for OnCombatStart delays**:
_This will be elaborated on in another comment._
```lua
function mod:OnCombatStart(delay)
  timerWithVarianceCD:Start(string.format("v%s-%s", 31.6-delay, 40-delay))
end
```

Added variance windows to some test bars for demonstration purposes.

Lastly, timer refreshes were slightly tweaked to be a bit more verbose and catch additional cases.

Demonstration:

https://github.com/user-attachments/assets/fd636e3c-f5ea-4684-bb87-f8ca379da758

Notes for thoughts:
- There is no GUI for this at this stage to tweak visuals. First, it is paramount to get the framework reviewed and stable to reach the final version.
- There will be cases where refactoring is needed (I left comments where I think this is necessary). Not done now for the same reason.
- `keep` argument is a remedy to catch timers going beyond their known variance window, but ideally, this requires a bit more care when adding to each mod, since there is always the need to account for proper cancellation where relevant. For this reason, I believe a more ellaborate way to debug/log these timers would be a perfect addition to complement this framework. Can be done at a later stage (left this note in a comment)
- I have **NOT** tested its impact on the new Tests/Playground mode. I assume this would need to be adapted as well.

### CODE REVIEW

**Comment by MysticalOS** [comment]
This is definitely of biggest use in classic, so I definitely want @emmericp to be one of reviewers/contributors to idea.

But of course retail will use it to

**Comment by Zidras** [comment]
> _This will be elaborated on in another comment._
These were all the approaches I've considered:
```lua
function mod:OnCombatStart(delay)
    timerCaptainsFlourishCD:Start(6-delay, 1) -- how to write variance with delay, let's assume "v6-10" - delay
end
```
*Lua note*: it's possible to concat and use numbers in %s, and drop the need to use `tostring`
1. Concatenations
```lua
function mod:OnCombatStart(delay)
    timerCaptainsFlourishCD:Start("v"..(6-delay).."-"..(10-delay), 1)
end
```
2. String.format

```lua
function mod:OnCombatStart(delay)
    timerCaptainsFlourishCD:Start(string.format("v%s-%s", 6-delay, 10-delay), 1)
end
```
3. Local function in each mod

```lua
local str = ""
local function varianceTimerStringWithDelay(delay, minTimer, maxTimer)
if not delay or not minTimer or not maxTimer then
  return -- error catching
end
local minTimerDelayed, maxTimerDelayed = minTimer-delay, maxTimer-delay

return str:format("v%s-%s", minTimerDelayed, maxTimerDelayed)

function mod:OnCombatStart(delay)
    timerCaptainsFlourishCD:Start(varianceTimerStringWithDelay(delay, 6, 10), 1)
end
```

4. DBM method for global use

```lua
-- In Core
do
  local str = ""
  function DBM:VarianceTimerStringWithDelay(delay, minTimer, maxTimer)
  if not delay or not minTimer or not maxTimer then
    return -- error catching
  end
  local minTimerDelayed, maxTimerDelayed = minTimer-delay, maxTimer-delay

  return str:format("v%s-%s", minTimerDelayed, maxTimerDelayed)
end
-- in mod
function mod:OnCombatStart(delay)
    timerCaptainsFlourishCD:Start(DBM:VarianceTimerStringWithDelay(delay, 6, 10), 1)
end
```
5. New pattern

_Adding another pattern to the mix_

I personally prefer number 2. It's readable code without much need to be fancy with optimizations. However, this should be reviewed by Lua gurus with deep understanding of GC management and performance in general.

**Comment by MysticalOS** [comment]
I'm sure you already noticed the luaLS error, the casttype error doesn't matter much but the global/misuse of fireevent is def a bug

**Comment by Zidras** [comment]
> I'm sure you already noticed the luaLS error, the casttype error doesn't matter much but the global/misuse of fireevent is def a bug

I did and pushed fix. I don't have LuaLS in my workflow, and I am not well versed in its syntax, so I leave the warnings to you, if you don't mind.

**Comment by Zidras** [comment]
> > I'm sure you already noticed the luaLS error, the casttype error doesn't matter much but the global/misuse of fireevent is def a bug
> 
> I did and pushed fix. I don't have LuaLS in my workflow, and I am not well versed in its syntax, so I leave the warnings to you, if you don't mind.

@MysticalOS , LuaLS complaining on unrelated code, which is on live branch too, so this is out of scope of this PR.

**Comment by MysticalOS** [comment]
it's complaining cause it needs to be rebased with changes i made yesterday. i can probably do that myself

**Comment by Zidras** [comment]
Slightly adjusted demo bars to showcase how the bar countdown ends on the **minTimer**

**Comment by Zidras** [comment]
Also, for merging, feel free to Squash and merge, with the initial description:

Fixes https://github.com/DeadlyBossMods/DBM-Unified/issues/265
Introduces variance framework onto the following methods:
- NewTimer
- newTimer
- Start

Usage syntax: `"v20.5-25.5"`

Added variance windows to some test bars for demonstration purposes.

Lastly, timer refreshes were slightly tweaked to be a bit more verbose and catch additional cases.

**Pull request merged**
