### PR TITLE
More modularization in core

### PR DESCRIPTION
**Pull request by emmericp**
Added a new PrototypeRegistry which is basically just a central table of "class" prototypes to make it easier to spread a class definitions across multiple files. Move all warning objects into this new prototype definition.

This should hopefully make it easier to add "TimerV2" etc in the future.

### CODE REVIEW

**Comment by MysticalOS** [comment]
DBM-Core/modules/objects/EnrageTimer.lua:18:38: accessing undefined variable 'abs'
Nani?

**Comment by Zidras** [comment]
> DBM-Core/modules/objects/EnrageTimer.lua:18:38: accessing undefined variable 'abs' Nani?

math.abs

Was previously cached on dbm core, but not in the new file

**Comment by emmericp** [comment]
`abs` is a global, luacheck just doesn't know about it. this failure was why i sent https://github.com/DeadlyBossMods/DeadlyBossMods/pull/1046 because i didn't feel like updating the luacheck file

**Comment by MysticalOS** [comment]
Throw this one in there
https://cdn.discordapp.com/attachments/419696269456572416/1232043217290264586/Screenshot_2024-04-22_at_2.58.48_PM.PNG?ex=66280529&is=6626b3a9&hm=1961ad61f2fb01e89ede4b3604eff21668f5a37db3e99ee8b93ca4c7d5f4f51d&

**Review by MysticalOS — APPROVED** [review]

**Comment by MysticalOS** [comment]
couldn't figure out how to resolve conflicts so I told it to just scrap any changes I made that caused them and merge. So whatever bugs I fixed will just have to be found again, but it's now merged

**Pull request merged**
